apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "k8s-agent.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "k8s-agent.fullname" . }}
    spec:
      serviceAccountName: {{ include "k8s-agent.fullname" . }}

      containers:
        - name: k8s-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- if .Values.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
          {{- end }}

          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: config
          configMap:
            name: {{ include "k8s-agent.fullname" . }}-config
